name: METdatadb CI/CD Workflow
on:
  push:
    branches:
      - develop
      - develop-ref
      - feature_*
      - main_*
      - bugfix_*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install Python dependencies
        run: python -m pip install --upgrade sphinx sphinx-gallery sphinx_rtd_theme
      - name: Build documentation
        continue-on-error: true
        run: ./.github/jobs/build_documentation.sh
      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: artifact/documentation
      - uses: actions/upload-artifact@v2
        with:
          name: documentation_warnings.log
          path: artifact/doc_warnings.log
          if-no-files-found: ignore
