# This workflow will install Python dependencies, run tests the specified Python version
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches:
      - develop
      - develop-ref
      - feature_*
      - main_*
      - bugfix_*
      - issue_*
      - gha_*
      - test_*
    paths-ignore:
      - 'docs/**'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '**/README.md'
      - '**/LICENSE.md'


  pull_request:
    types: [ opened, reopened, synchronize ]


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # adopted from 
      # https://mariadb.org/mariadb-server-docker-official-images-healthcheck-without-mysqladmin/
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MARIADB_MYSQL_LOCALHOST_USER: 1
          MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
        ports:
          - 3306
        healthcheck:
          test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
          start_period: 1m
          start_interval: 10s
          interval: 1m
          timeout: 5s
          retries: 3

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Retrieve METcalcpy repository develop branch
        run: |
          python -m pip install --upgrade pip
          metcalcpy_dir="${RUNNER_WORKSPACE}/METcalcpy"
          git clone https://github.com/dtcenter/METcalcpy ${metcalcpy_dir}
          git -C ${metcalcpy_dir} checkout develop
          python -m pip install -e ${metcalcpy_dir}


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest>=7.1.1
          python -m pip install netcdf4==1.6.2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install pytest-cov

      #   Checking the branch name, not necessary but useful when setting things up.
      #     - name: Extract branch name
      #       shell: bash
      #       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #       id: extract_branch


      - name: Test with pytest
        run: |
          coverage run --append -m pytest METreformat
          coverage run --append -m pytest METreadnc
          coverage run --append -m pytest METdbLoad/test
          coverage report -m
          echo "Finished unit tests and coverage"

